main: org.winlogon.simplewarp.WarpPlugin
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.1"
author: walker84837
description: SimpleWarp - A simple /warp plugin
commands:
  warp:
    description: Base command for /warp
    usage: "For a list of commands, type /warp help"
permissions:
  warp.admin:
    description: Permissions to create, edit and delete warps
    default: false
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true
